version: '3.7'

services:
  app-windows:
    image: cdrx/pyinstaller-windows
    container_name: MBDLR-windows
    volumes:
      - .:/src

  app-windows-zip:
    container_name: MBDLR-windows-zip
    build:
      dockerfile: Dockerfile.dist-zip
      context: .
    volumes:
    - ./dist/windows:/app
