"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from setuptools import setup

os.environ['QT_DEBUG_PLUGINS'] = '1'

plugin_path_old = '/Users/simonprive/.virtualenvs/mbdlr/lib/python3.7/site-packages/PySide2/Qt/PlugIns'
plugin_path_new = '/Users/simonprive/Dropbox/programming/projects/mixcloud_bulk_downloader/dist/main.app/Contents/plugins/platforms'

os.environ['QT_PLUGIN_PATH'] = plugin_path_new
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = plugin_path_new

APP = ['main.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
